# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20160531_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='unit_price',
            field=models.FloatField(),
        ),
    ]
